config/routes.rb
Rails.application.routes.draw do
  root "hospitals#index"
  resources :hospitals do
    resources :departments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord
  validates :department_code, :department_name, presence: true
  belongs_to :hospital
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :departments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @hospital = Hospital.find(params[:hospital_id])
    @departments = @hospital.departments
  end

  # GET /departments/1 or /departments/1.json
  def show
    @hospital = Hospital.find(params[:hospital_id])
    department = @hospital.departments
  end

  # GET /departments/new
  def new
    @hospital = Hospital.find(params[:hospital_id])
    @department = @hospital.departments.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @hospital = Hospital.find(params[:hospital_id])
    @department = @hospital.departments.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to hospital_departments_path(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy!

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:department_code, :department_name, :hospital_id)
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: %i[ show edit update destroy ]

  # GET /hospitals or /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1 or /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals or /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to hospital_url(@hospital), notice: "Hospital was successfully created." }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1 or /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to hospital_url(@hospital), notice: "Hospital was successfully updated." }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1 or /hospitals/1.json
  def destroy
    @hospital.destroy!

    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: "Hospital was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hospital_params
      params.require(:hospital).permit(:name, :contact, :email, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Department code:</strong>
    <%= department.department_code %>
  </p>

  <p>
    <strong>Department name:</strong>
    <%= department.department_name %>
  </p>

  <p>
    <strong>Hospital:</strong>
    <%= department.hospital.name %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with model: [@hospital, @department] do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :department_code, style: "display: block" %>
    <%= form.text_field :department_code %>
  </div>

  <div>
    <%= form.label :department_name, style: "display: block" %>
    <%= form.text_field :department_name %>
  </div>

  <div>
    <%= form.label :hospital_id, style: "display: block" %>
    <%= form.text_field :hospital_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show this department", @department %> |
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departments</h1>

<div id="departments">
  <% @departments.each do |department| %>
    <%= render department %>
    <p>
      <%#= link_to "Show this department", department %>
    </p>
  <% end %>
</div>

<%= link_to "New department",  new_hospital_department_path(params[:hospital_id]) %>
<%= link_to "Back to hospital",  hospitals_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Back to departments",  hospital_departments_path  %>
</div>

app/views/departments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @department %>

<div>
  <%= link_to "Edit this department", edit_department_path(@department) %> |
  <%= link_to "Back to departments", departments_path %>

  <%= button_to "Destroy this department", @department, method: :delete %>
</div>

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital) do |form| %>
  <% if hospital.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
        <% hospital.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitals/_hospital.html.erb
<div id="<%= dom_id hospital %>">
  <p>
    <strong>Name:</strong>
    <%= hospital.name %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= hospital.contact %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= hospital.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= hospital.address %>
  </p>

</div>

app/views/hospitals/edit.html.erb
<h1>Editing hospital</h1>

<%= render "form", hospital: @hospital %>

<br>

<div>
  <%= link_to "Show this hospital", @hospital %> |
  <%= link_to "Back to hospitals", hospitals_path %>
</div>

app/views/hospitals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hospitals</h1>

<table>
  <thead>
    <tr>
      <th>Hospital Name </th>
      <th>Address</th>
      <th>Contact</th>
      <th>Email</th>
      <%# <th Colspan="3">Action</th> %>
    </tr>
  </thead>
  <tbody>
    <% @hospitals.each do |hospital| %>
    <tr>
      <td><%= link_to "#{hospital.name}", hospital %>
      <td><%= hospital.address %></td>
      <td><%= hospital.contact %></td>
      <td><%= hospital.email %></td>
      <td><%= link_to "Departments",  hospital_departments_path(hospital) %></td>
    </tr>
    <% end %>
  </tbody>

</table>

<%# <div id="hospitals"> %>
  <%# @hospitals.each do |hospital| %>
    <%#= render hospital %>
    <%# <p> %>
      <%#= link_to "Show this hospital", hospital %>
    <%# </p> %>
  <%# end %>
<%# </div> %>

<%= link_to "New hospital", new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New hospital</h1>

<%= render "form", hospital: @hospital %>

<br>

<div>
  <%= link_to "Back to hospitals", hospitals_path %>
</div>

app/views/hospitals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hospital %>

<div>
  <%= link_to "Edit this hospital", edit_hospital_path(@hospital) %> |
  <%= link_to "Back to hospitals", hospitals_path %>

  <%= button_to "Destroy this hospital", @hospital, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospitalmanagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
          <%= link_to "Hospitals", hospitals_path, class: "btn btn-outline-primary" %>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to "Departments",  hospital_departments_path, class: "btn btn-outline-primary" %>

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Receptionist</a></li>
            <li><a class="dropdown-item" href="#">Doctor</a></li>
            <li><a class="dropdown-item" href="#">Patient</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>